menu:
  Home:
  Archives: archives
  About: about.html
  Contact: contact.html

widgets:
- search
- category
- tag

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: 
  twitter: 
  google: 
  pinterest: 

fancybox: true

google_analytics:
rss:

comment_provider: disqus
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light

disqus_shortname: betterprogrammer

favicon: favicon.ico